## üóÉÔ∏è Introduction to Databases

---

#### üìö What is a Database?

A **database** is an organised collection of data.  
It allows you to **store**, **retrieve**, **update**, and **delete** information easily.

Instead of saving data in many separate files, databases organize data in **tables**.

---

#### üß± Key Concepts

| Term    | Meaning |
|---------|--------|
| **Table** | A collection of related data, like a spreadsheet. |
| **Field** | A single piece of data (like a column). Example: name, age. |
| **Record** | A complete set of fields (like a row). Example: one student's details. |
| **Primary Key** | A unique identifier for each record (e.g., student ID). Each record must have a different primary key. |
| **Data Types** | The type of data stored in a field, such as: <br> - `INTEGER` for numbers <br> - `TEXT` for words <br> - `REAL` for decimal numbers <br> - `DATE` for dates |

---

#### üìù Example: A Simple Table

Imagine a database to store information about **students**.

| ID  | Name  | Age | Grade |
|----|-------|-----|-------|
| 1  | Alice | 14  | A     |
| 2  | Bob   | 15  | B     |

- **Table**: Students
- **Fields**: ID, Name, Age, Grade
- **Records**: Alice's data, Bob's data

---
#### üìã Flat-File Database

A **flat-file database** is the simplest form:
- All data is kept in one table (no complex links).
- Ideal for small datasets like a list of books, students, pets, etc.

Example: a CSV file or a simple SQLite table.

---

# üñ•Ô∏è Basic SQL (Structured Query Language)

SQL is the language we use to **talk to databases**.  
It lets you **create tables**, **add data**, and **get data** back.

---

## üèóÔ∏è Creating the database and data Tables

Creating a database depends on the DBMS being used.  In our case we will simply create a db file.

create a file and name it as **students.db**

---
```sql
CREATE TABLE tblstudents (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT,
    age INTEGER,
    grade TEXT
);
```
This creates a table called students with 4 fields: id, name, age, grade.

id is the Primary Key (it must be unique for each student).

---

#### ‚ûï Inserting Data

```sql
INSERT INTO tblstudents (name, age, grade)
VALUES ('Freddie', 17, 'A');

INSERT INTO tblstudents (name, age, grade)
VALUES ('Corrina', 16, 'B');
```
---
#### üîé Selecting (Retrieving) Data
Get all the records from the students table:
```sql 
SELECT * FROM tblstudents;
```
| ID  | Name  | Age | Grade |
|----|-------|-----|-------|
| 1  | Freddie | 17  | A     |
| 2  | Corrina   | 16  | B     |

Get only students who have an A grade:

```sql
SELECT name, grade
FROM tblstudents
WHERE grade = 'A';
```
| Name  | Grade |
|-------|-------|
| Freddie | A     |

#### ‚úèÔ∏è Updating Data
If a student improves their grade, you can update their record.

```sql
UPDATE tblstudents
SET grade = 'A'
WHERE name = 'Corinna';
```
This changes Corrina's grade to A.
You can also update by ID (which is safer):
```sql
UPDATE tblstudents
SET grade = 'A+'
WHERE id = 2;

### Python Database Integration

#### 1: Create the database file
- Since we are going to be working with SQLite, make sure the database is saved with a students.db extension

#### 2: Import the required module (s)
```python
import sqlite3
```
#### 3. Connect to the database
Since this is something you will be doing often, you can put your code into a re-usable function

```python
  def dbconnection(dbfile):
    '''creates connection and cursor objects which allow you to work with the database'''
    conn = sqlite3.connect(dbfile)
    cur = conn.cursor()
    print("Connection was successful")
    return conn, cur
```
#### 4. Create the data tables if they do not already exist

```python
#create the table if it does not exist
  conn, cur = dbconnection("students.db")
  cur.execute('''
      CREATE TABLE IF NOT EXISTS tblstudents (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      name TEXT,
      age INTEGER,
      grade TEXT
  )
  ''')
  print("The table was created successfully")
```
#### 5. Run the required queries

Note that if you run a single sql state you can use cursor.execute(query) - the parameter is a single query string

If you run multiple sql statements  then use cursor.executescript(query)

```python
#for multiple sql statements use cur.executescript
cur.executescript('''
INSERT INTO tblstudents (name, age, grade)
VALUES ('Freddie', 17, 'A');

INSERT INTO tblstudents (name, age, grade)
VALUES ('Corrina', 16, 'B');
''')
```
#### 6. Select queries - interrogate the database and display results

```python
#1. Execute the query
cur.execute('''
    SELECT * FROM tblstudents;

''')
#2. Fetch records
rows = cur.fetchall()

#print results
for row in rows:
    print(row)
conn.close()
```

##### You can create custom functions that can run and display query results
```python
def select_display_results(dbpath,query_string):
    conn,cur = dbconnection(dbpath)
    #1. Execute the query
    cur.execute(f'''{query_string}''')
    #2. Fetch all rows
    rows = cur.fetchall()
    #print data
    for row in rows:
        print(row)

select_display_results("students.db","SELECT * FROM tblstudents")
```

#### 7. Select query with a criteria

Here I am using the custom function created in the previous task

select_display_results("students.db","SELECT name, grade FROM tblstudents WHERE grade = 'A'")

#### Mini Challenge

Can you print off the data under the correct field headings
- Hint: cur.description returns an array with all the field names

### üí° Challenge: University Research Project Challenge

**Scenario**
You are helping a university design a system to track student research projects.  
Each project has:

- Project ID (Primary Key)
- Student Name (required i.e. NOT NULL)
- Project Title (required i.e. NOT NULL)
- Supervisor Name
- Field of Study (e.g., Biology, Computer Science, Engineering)
- Year (e.g., 2025)

---
*Tasks*

---
#### üèóÔ∏è 1. Create the SQLite Database

**Steps:**
1. Create a notebook in which you will run code to manipulate the database e.g "python_sql_integration.ipynb"
2. Add a new code cell and type the following Python code to create a blank database file:

```python
import sqlite3
import os

# This will create a database file named 'university_projects.db'
if not os.path.exists('university_projects.db'):
  conn = sqlite3.connect('university_projects.db')
  print("The database was successfully created")
  conn.close()
else:
  print("The database already exists. No action taken")